services:
  mongo:
    image: 'mongo'
    container_name: 'mongo'
    hostname: 'mongo'
    domainname: 'books.com'
    restart: 'always'
    environment:
    - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-user}'
    - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-ZHNhZGFkYWRhc2Rh}'
    ports:
    - '27017:27017'
    volumes:
    - 'mongo_data:/data/db'

  app:
    build: .
    container_name: 'library-app'
    depends_on:
    - mongo
    environment:
    - 'MONGO_URI=mongodb://${MONGO_USER:-user}:${MONGO_PASSWORD:-ZHNhZGFkYWRhc2Rh}@mongo:27017/?authSource=admin'
    - 'MONGO_DATABASE=${MONGO_DATABASE:-library}'
    stdin_open: true
    tty: true

volumes:
  mongo_data:
